// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_compare_json`, `build_report_json`, `build_turn_json`, `emit`, `outcome_json`, `parse_algo`, `playtest_session`, `query_preview`, `run_batch_impl`, `run_compare_impl`, `run_compare_phase`, `run_forget_impl`, `run_suite_impl`, `stage_name`, `trace_json`, `trace_node`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BatchEvent`, `BatchReportJson`, `CompareAggregateJson`, `CompareCaseJson`, `CompareEvent`, `CompareReportJson`, `DatasetEntryJson`, `DatasetMetaJson`, `DatasetResultJson`, `ForgetEvent`, `ForgetObserverCaseJson`, `ForgetReportJson`, `InspectEntriesJson`, `InspectEntryJson`, `InspectLinkJson`, `ModelStatusJson`, `OutcomeJson`, `ParamSpecJson`, `PerQueryJson`, `PlaytestSession`, `ReportJson`, `RunEvent`, `RunJson`, `TraceJson`, `TraceNodeJson`, `TurnJson`

/// 递归扫描目录下的全部 question.json 数据集文件。
Future<String> scanDatasetsJson({required String dir}) =>
    RustLib.instance.api.crateApiScanDatasetsJson(dir: dir);

/// 解析 question.json 头部元数据（供数据集预览卡）。
Future<String> datasetMetaJson({required String path}) =>
    RustLib.instance.api.crateApiDatasetMetaJson(path: path);

/// 可调参数规格（参数表单用；与 engine 读取的 key 一一对应）。
Future<String> defaultParamsJson() =>
    RustLib.instance.api.crateApiDefaultParamsJson();

/// 清空取消标志（每次运行前调用）。
Future<void> resetCancel() => RustLib.instance.api.crateApiResetCancel();

/// 运行单个检索套件，进度与结果通过流推送。
Stream<String> runSuite({
  required String algo,
  required String dataset,
  required String paramsJson,
}) => RustLib.instance.api.crateApiRunSuite(
  algo: algo,
  dataset: dataset,
  paramsJson: paramsJson,
);

/// 批量运行目录下全部检索数据集（4 worker 并发，逐数据集推流）。
Stream<String> runBatch({
  required String dir,
  required String mode,
  required String paramsJson,
}) => RustLib.instance.api.crateApiRunBatch(
  dir: dir,
  mode: mode,
  paramsJson: paramsJson,
);

/// 对比运行：同一数据集依次跑 embedding 与 full pipeline，产出逐用例对比报告。
Stream<String> runCompare({
  required String dataset,
  required String paramsJson,
}) => RustLib.instance.api.crateApiRunCompare(
  dataset: dataset,
  paramsJson: paramsJson,
);

/// 检视数据集（结构化条目）：复用 engine/inspect 的解析（与 TUI inspect 一致），
/// 输出图节点/查询用例的分层条目供 GUI 卡片渲染。
Future<String> inspectEntriesJson({required String path}) =>
    RustLib.instance.api.crateApiInspectEntriesJson(path: path);

/// 检视任意 JSON 数据集文件：检测类型（question/graph/json）并返回完整解析数据。
Future<String> inspectFileJson({required String path}) =>
    RustLib.instance.api.crateApiInspectFileJson(path: path);

/// 运行遗忘套件（mask=遮罩 / revise=遮罩补全 / pipeline=全管线）。
Stream<String> runForget({required String mode, required String dataset}) =>
    RustLib.instance.api.crateApiRunForget(mode: mode, dataset: dataset);

/// 查询模型可用性：先探测运行中的 llama-server，无则查找本地缓存模型（不启动）。
///
/// 所有需要模型的地方共用同一套来源决策（见 `soul_tune::engine::llm::resolver`）。
Future<String> modelStatusJson() =>
    RustLib.instance.api.crateApiModelStatusJson();

/// 启动 playtest：加载角色图 + LLM。
/// 参数可以是图目录（须含 graph.json）或 graph.json 文件本身（取其父目录）。
/// `user_role` 非空时作为对话中对方（人类）的身份注入。
/// LLM 来源统一解析：先复用运行中的 llama-server，无则自动拉起本地缓存模型，
/// 都没有则返回明确错误（见 `soul_tune::engine::llm::resolver`）。
Future<String> playtestStart({
  required String graphDir,
  required String userRole,
}) => RustLib.instance.api.crateApiPlaytestStart(
  graphDir: graphDir,
  userRole: userRole,
);

/// 记录一轮对话的人工投票：0=embedding 更好 / 1=full 更好 / 2=持平。
Future<void> playtestVote({required BigInt turnIndex, required int pick}) =>
    RustLib.instance.api.crateApiPlaytestVote(turnIndex: turnIndex, pick: pick);

/// 结束 playtest 会话（关闭 llama-server 子进程）。
Future<void> playtestFinish() => RustLib.instance.api.crateApiPlaytestFinish();

/// 处理一轮对话：生成查询 → 双管线检索 → LLM 回复，结果以单条 JSON 推流。
Stream<String> playtestTurn({required String userMessage}) =>
    RustLib.instance.api.crateApiPlaytestTurn(userMessage: userMessage);
