[package]
name = "soul-mem-query"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
candle-core = {version = "=0.9.1"}
embed_anything = "0.6.7"
rayon = { workspace = true }
text-splitter = { workspace = true }

soul-mem-core = {path = "../soul-mem-core"}

[dev-dependencies]
tokio = { workspace = true }
