[package]
name = "soul-mem-query"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
candle-core = { workspace = true }
embed_anything = "0.7.1"
rayon = "1.10.0"
text-splitter = "0.29.3"

soul-mem-core = {path = "../soul-mem-core"}

[dev-dependencies]
tokio = { workspace = true }
