[package]
name = "soul-tune"
version = "0.1.0"
edition = "2024"
description = "Test framework for SoulMem."

[dependencies]
color-eyre = "0.6.5"
nucleo = "0.5.0"
parking_lot = "0.12.5"
ratatui = "0.30.1"
ratatui-textarea = "0.9.1"
serde_json.workspace = true
soul-mem-core = { path = "../soul-mem-core" }
soul-mem-algo = { path = "../soul-mem-algo" }
soul-mem-query = { path = "../soul-mem-query" }
soul-mem-runtime = { path = "../soul-mem-runtime" }
serde.workspace = true
rayon = "1.10.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
rand = "0.8"
async-openai = { version = "0.32.4", features = ["chat-completion"] }
