[package]
name = "soul-mem-algo"
version = "0.1.0"
edition = "2024"

[dependencies]
soul-mem-core = { path = "../soul-mem-core" }
soul-mem-query = { path = "../soul-mem-query" }
soul-mem-runtime = { path = "../soul-mem-runtime" }
petgraph = { workspace = true }
ordered-float = "5.0.0"

chrono = { workspace = true }
parking_lot = { workspace = true }
jieba-rs = { workspace = true }
dashmap = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
async-openai = { workspace = true }
dotenvy = { workspace = true }
