[package]
name = "soul-mem-runtime"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
soul-mem-core = { path = "../soul-mem-core" }
soul-mem-query = { path = "../soul-mem-query" }
serde = { workspace = true }
thiserror = { workspace = true }
petgraph = { workspace = true }

chrono = { workspace = true }
anyhow = { workspace = true }

serde_json = { workspace = true }

http = "1.4.0"
secrecy = "0.10.3"
log = "0.4.27"
dotenvy = "0.15.7"
async-openai = { version = "0.32.4", features = ["chat-completion"] }
parking_lot = { version = "0.12.4", features = ["serde"] }
async-trait = { workspace = true }
uuid = { workspace = true }
surrealdb = { version = "3.2.4", features = ["kv-surrealkv"] }

[dev-dependencies]
tokio = { workspace = true }
soul-mem-algo = { path = "../soul-mem-algo" }
